#!/bin/sh

if command -v pamixer &>/dev/null; then
    if [ true == $(pamixer --get-mute) ]; then
        echo 0
        exit
    else
        pamixer --get-volume
    fi
else
    pactl get-sink-volume @DEFAULT_SINK@ | awk -F '[^0-9]+' '/left:/{print $3}'
fi
